version: '3'

dotenv:
- '.env'

tasks:
  plan:
    dir: terraform/
    cmds:
    - terraform init
    - terraform plan --out .tfplan

  apply:
    dir: terraform/
    cmds:
    - terraform fmt --recursive
    - terraform apply .tfplan

