# Server plan.
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-upgrade-server
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/control-plane
      operator: In
      values:
      - "true"
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade
  # Version numbers can be found at:
  # https://github.com/k3s-io/k3s/releases
  version: v1.28.4-rc1+k3s1
---
# Agent plan.
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-upgrade-agent
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/control-plane
      operator: DoesNotExist
  prepare:
    args:
    - prepare
    - server-plan
    image: rancher/k3s-upgrade
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade
  # Version numbers can be found at:
  # https://github.com/k3s-io/k3s/releases
  version: v1.28.4-rc1+k3s1

